title: Sylvia Nwakanma
description: "Project portfolio featuring UPDATE?<br> | Digital Mapping <br> | Coding <br> | Data Analysis <br> | Technical Writting <style>footer p { display: none !important; }</style>"
show_downloads: false
is_project_page: false
theme: jekyll-theme-minimal
